services:
  - type: web
    name: krabsleads-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONDAY_API_KEY
        sync: false
      - key: MONDAY_BOARD_ID
        sync: false
      - key: ONETIMESECRET_USERNAME
        sync: false
      - key: ONETIMESECRET_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: DRIVER_TELEGRAM_ID
        sync: false
      - key: GROUP_TELEGRAM_ID
        sync: false
      - key: SUPERVISORY_TELEGRAM_ID
        sync: false


